services:
  behaviot:
    image: behaviot
    container_name: behaviot
    volumes:
      - .:/home/user/BehavIoT
    # Update to the desired command
    command: ["python3", "/home/user/BehavIoT/event_inference/pipeline/s6_binary_model_whostname.py", "-i", "/home/user/BehavIoT/event_inference/data/ours-features/", "-o", "/home/user/BehavIoT/event_inference/data/ours-binary-whostname/"]
    restart: no
